### ISSUE TITLE
Unable to parse array of strings without quotes

### ISSUE THREAD

**Issue by lingolab2** [koalaylj/xlsx2json#39]
Excellent tool. I had used it a year ago. Now the same XLSX file does not parse due to lack of quotes in the string-array fields. Is there a config-option to make it backward compatible? 

```
./export.sh 
parsing excel: myXLSfile.xlsx
  * sheet:  sheetName
undefined:1
([a,b,c])
  ^
```

```
ReferenceError: a is not defined
    at eval (eval at parseJsonObject (/Users/mohideennoordeen/Downloads/ProKanjiMigration/xlsx2json-master/lib/parser.js:10:10), <anonymous>:1:3)
    at eval (<anonymous>)
    at parseJsonObject (/Users/mohideennoordeen/Downloads/ProKanjiMigration/xlsx2json-master/lib/parser.js:10:10)
    at parseRow (/Users/mohideennoordeen/Downloads/ProKanjiMigration/xlsx2json-master/lib/parser.js:236:24)
    at parseSheet (/Users/mohideennoordeen/Downloads/ProKanjiMigration/xlsx2json-master/lib/parser.js:137:22)
    at workbook.forEach.sheet (/Users/mohideennoordeen/Downloads/ProKanjiMigration/xlsx2json-master/lib/parser.js:332:26)
    at Array.forEach (<anonymous>)
    at Object.parseWorkbook (/Users/mohideennoordeen/Downloads/ProKanjiMigration/xlsx2json-master/lib/parser.js:316:14)
    at Object.toJson (/Users/mohideennoordeen/Downloads/ProKanjiMigration/xlsx2json-master/lib/xlsx-to-json.js:169:34)
    at files.forEach.item (/Users/mohideennoordeen/Downloads/ProKanjiMigration/xlsx2json-master/index.js:63:14)

```

**Comment by zk-luke** [comment]
really sorry for that， it's a break update and cannot make it backward compatible for now.
array should be like this ["a","b","c"] now.
